In [10]:
%load_ext autoreload
%autoreload 2

In [11]:
import torch
import torchvision
import torchvision.transforms as transforms
from dataset.get_dataloader import get_dataloader,loader2vec, vec_dis


train_loader, test_loader = get_dataloader(chose="cifar10")


Files already downloaded and verified
Files already downloaded and verified


In [2]:
flattened_images = loader2vec(train_loader=train_loader)

# flattened_images现在包含整个训练集中的图像向量，形状为(N, 3 * 224 * 224)，其中N是训练集的大小


In [3]:
print("flattened_images shape:", flattened_images.shape)

print("First 5 flattened image vectors:")
for i in range(5):
    print(flattened_images[i])


flattened_images shape: torch.Size([50000, 3072])
First 5 flattened image vectors:
tensor([ 1.9907,  2.3590,  2.4172,  ..., -1.8313, -1.9679, -2.0655])
tensor([-2.2740, -2.2546, -2.2740,  ..., -1.4606, -1.2851, -1.5192])
tensor([ 0.4011,  0.5950,  0.7113,  ..., -1.4997, -1.4997, -1.5582])
tensor([ 0.0716, -0.2967, -0.8395,  ...,  0.1197,  1.1342,  1.3293])
tensor([-2.1383, -2.0414, -1.9444,  ...,  0.4514,  0.5684,  0.6660])


In [5]:

l2_distances = vec_dis(data_matrix=flattened_images, distance="l2")
l1_distances = vec_dis(data_matrix=flattened_images, distance="l1")


In [ ]:
# import numpy as np

# # 读取 L2 范数距离矩阵
# loaded_l2_distances = np.load('l2_distances.npy')

# # 读取 L1 范数距离矩阵
# loaded_l1_distances = np.load('l1_distances.npy')


In [ ]:
from dataset.data2betti import distance_betti

l2_betti_number = distance_betti(distances=l2_distances)
l1_betti_number = distance_betti(distances=l1_distances)